apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-xpukgtel
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-xpukgtel:4ce9f3747edfe1961f89ce69ce1ac8435f69c851@sha256:490a9614dfeac28ba9cf12398451c8baceedb5a842bb7f6f15e3f9fb715c20d0
          name: container-image
